YAML Support for spring security saml rename of identityprovider to a…
openrewrite/rewrite-spring pull request #205
Opened 2022-07-01 08:26 UTC by sanagaraj-pivotal

This PR handles the property move of spring security saml:
`spring.security.saml2.relyingparty.registration.(any).identityprovider` is moved to `spring.security.saml2.relyingparty.registration.(any).assertingparty`

You can find more info on [official spring docs](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#deprecations-in-spring-boot-27)
Here are the test cases this PR handles: 

### When there is only one identity provider:
![image](https://user-images.githubusercontent.com/59915704/176855480-f2b1d10f-c8c0-4816-abde-1ca5946adc23.png)

### When there are multiple identity provider:
![image](https://user-images.githubusercontent.com/59915704/176855705-9920fb2c-b626-4d74-9a44-ffd58611d170.png)

### Move identity provider only when a hierarchy pattern is detected
![image](https://user-images.githubusercontent.com/59915704/176855900-c689553e-7ca8-4500-b683-2aac05e8569a.png)
![image](https://user-images.githubusercontent.com/59915704/176856057-bce42342-4203-4959-a4ec-f47d6ecddb1a.png)

2022-07-01 14:13 UTC, jkschneider commented
Thanks @sanagaraj-pivotal (and welcome!). It's great to see a variation on property changes we've made before, one where there can be an `(any)` component of the matching property. I expanded the core recipe `org.openrewrite.yaml.ChangePropertyKey` to support globbable property matches so that this recipe can actually turn into just a declarative one. The recipe itself can be built up on `public.moderne.io` using the builder feature:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/1697736/176911118-cf8be56e-1693-4e49-b5c4-e0164fd67fee.png">

Click `Add to Builder` and on the builder view we see:

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/1697736/176911233-c4005607-3cf8-4597-bb1f-bd91fb833fbc.png">

There is a copy-paste widget in the top right that allows us to copy the YAML of this recipe for inclusion here in `rewrite-spring`:

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.spring.SAMLRelyingPartyPropertyYamlMove
displayName: Migrate SAML relying party property to `assertingparty`
description: Renames
  `spring.security.saml2.relyingparty.registration.*.identityprovider`
  to  `spring.security.saml2.relyingparty.registration.*.assertingparty`.
recipeList:
  - org.openrewrite.yaml.ChangePropertyKey:
      oldPropertyKey: spring.security.saml2.relyingparty.registration.*.identityprovider
      newPropertyKey: assertingparty
      relaxedBinding: true
```

2022-07-04 13:39 UTC, sanagaraj-pivotal commented
Hello @jkschneider 
We had a little road bump following `ChangePropertyKey` recipe.
for the quoted recipe parameters above: following is the input and output:

Input:
![image](https://user-images.githubusercontent.com/59915704/177165147-f40f579e-bf28-4330-9ecd-98d9f03be1b6.png)

Expected and actual yml:

![image](https://user-images.githubusercontent.com/59915704/177166597-e5e0594a-fe7d-4bc0-9889-b92a83848120.png)


assertingparty is not changed in place of identity provider.
assertingparty will become root of yml document.

What we actually need in wishful thinking way is:
an ability to back reference using a variable.
```
recipeList:
  - org.openrewrite.yaml.ChangePropertyKey:
      oldPropertyKey: spring.security.saml2.relyingparty.registration.(*).identityprovider
      newPropertyKey: spring.security.saml2.relyingparty.registration.$1.identityprovider
      relaxedBinding: true
```

We also tried with ChangeKey Recipe which seem to change yml mapping in place, even with this we couldnt get wild card working:

example:
for this input:
![image](https://user-images.githubusercontent.com/59915704/177165799-54cf162c-ae52-42eb-9ba8-800a7f97fad4.png)

Following ChangeKeyRecipe works ✅
```
recipeList:
  - org.openrewrite.yaml.ChangeKey:
      oldKeyPath: $.spring.security.saml2.relyingparty.registration.idpone.identityprovider
      newKey: assertingparty
```
_(notice the hardcoded idpone)_
Following ChangeKeyRecipe **Does not** work ❌
```
recipeList:
  - org.openrewrite.yaml.ChangeKey:
      oldKeyPath: $.spring.security.saml2.relyingparty.registration.*.identityprovider
      newKey: assertingparty
```

is there a way to wildcard ChangeKey or a way to reference back wild cards in ChangePropertyKey, or can we accept this PR as is?

Thanks,
Sandeep N

2022-07-12 17:48 UTC, traceyyoshima commented
Hi @sanagaraj-pivotal,

> is there a way to wildcard ChangeKey or a way to reference back wild cards in ChangePropertyKey, or can we accept this PR as is?

Yes, you may update `identityprovider` with `ChangeKey("$.spring.security.saml2.relyingparty.registration.*[?(@.identityprovider)]", "assertingparty", null)`

2022-07-12 18:08 UTC, traceyyoshima requested changes
I think this recipe may be replaced by: `ChangeKey("$.spring.security.saml2.relyingparty.registration.*[?(@.identityprovider)]", "assertingparty", null)`

2022-07-13 22:42 UTC, traceyyoshima commented
Closing this PR.

I added the `ChangeKey` recipe in `spring-boot-configuration-migration-manual.yaml`. 048177758c33378e8e9ebb23924d42746495cf9c

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.spring.boot2.SpringBootPropertiesManual_2_7
displayName: Migrate additional Spring Boot properties to 2.7
description: Migrate properties found in `application.properties` and `application.yml` which are not generated automatically from Spring Boot's `additional-spring-configuration-metadata.json` file.
recipeList:
  # Change: spring.security.saml2.relyingparty.registration.{id}.identityprovider To: spring.security.saml2.relyingparty.registration.{id}.assertingparty
  - org.openrewrite.java.spring.boot2.SamlRelyingPartyPropertyApplicationPropertiesMove # Property files.
  - org.openrewrite.yaml.ChangeKey: # Yaml files
      oldKeyPath: $.spring.security.saml2.relyingparty.registration.*[?(@.identityprovider)]
      newKey: assertingparty

```

2022-07-13 22:42 UTC, closed without merging

2022-07-14 09:20 UTC, ashakirin commented
@traceyyoshima: yep, your update covers all my test cases, agree with closing PR
thanks!

2022-07-14 10:07 UTC, ashakirin commented
Added the test for this specific case: https://github.com/openrewrite/rewrite/pull/2042